/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Input {
  tomorrow: string;
  city: string;
  data: {
    name: string;
    sunrise: string;
    snaps: {
      time: number;
      fog: boolean;
      temperature: number;
      dewPoint: number;
      windSpeed: number;
      gusts: number;
      visibility: number;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
